ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REFRESH_TOKEN_REUSED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LOGOUT_ALL';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SESSION_REVOKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RESET_PASSWORD_SUCCESS';
